export type MarketingQuestionType =
  | "text"
  | "textarea"
  | "number"
  | "date"
  | "single"
  | "multi";

export type MarketingQuestion = {
  id: string;
  section: string;
  prompt: string;
  helper?: string;
  placeholder?: string;
  type: MarketingQuestionType;
  options?: string[];
};

export const marketingSections = [
  "School overview",
  "Admission goals",
  "Target audience",
  "Competitors",
  "Marketing",
  "Lead management",
  "Admission process",
  "Technology",
  "Content assets",
  "Branding",
  "Reviews",
  "AI automation priorities",
  "Budget & timeline",
  "Success metrics",
] as const;

export const marketingQuestions: MarketingQuestion[] = [
  {
    id: "school-vision",
    section: "School overview",
    prompt: "What is the vision and mission of your school?",
    placeholder: "Share Sri Sri Academy's vision and mission",
    type: "textarea",
  },
  {
    id: "school-difference",
    section: "School overview",
    prompt: "What makes your school different from competitors?",
    placeholder: "Academic approach, values, campus, outcomes, or student experience",
    type: "textarea",
  },
  {
    id: "school-curriculum",
    section: "School overview",
    prompt: "Which curriculum do you offer?",
    type: "multi",
    options: ["CBSE", "ICSE", "IB", "State", "Other"],
  },
  {
    id: "school-grades-open",
    section: "School overview",
    prompt: "Which grades are open for admissions?",
    placeholder: "List all grades currently accepting applications",
    type: "text",
  },
  {
    id: "school-student-strength",
    section: "School overview",
    prompt: "What is your current student strength?",
    placeholder: "Current number of enrolled students",
    type: "number",
  },
  {
    id: "school-capacity",
    section: "School overview",
    prompt: "What is your maximum student capacity?",
    placeholder: "Maximum number of students the school can support",
    type: "number",
  },
  {
    id: "school-admissions-this-year",
    section: "School overview",
    prompt: "How many admissions do you want this academic year?",
    placeholder: "Target number of new admissions",
    type: "number",
  },
  {
    id: "admissions-monthly-enquiries",
    section: "Admission goals",
    prompt: "How many enquiries do you receive monthly?",
    placeholder: "Average enquiries per month",
    type: "number",
  },
  {
    id: "admissions-monthly-conversions",
    section: "Admission goals",
    prompt: "How many admissions do you convert monthly?",
    placeholder: "Average confirmed admissions per month",
    type: "number",
  },
  {
    id: "admissions-target",
    section: "Admission goals",
    prompt: "What are your target admissions?",
    placeholder: "Share the target and academic period",
    type: "text",
  },
  {
    id: "admissions-grades-needed",
    section: "Admission goals",
    prompt: "Which grades need admissions most?",
    placeholder: "List priority grades",
    type: "text",
  },
  {
    id: "admissions-peak-months",
    section: "Admission goals",
    prompt: "Which months generate the highest enquiries?",
    placeholder: "For example: October to February",
    type: "text",
  },
  {
    id: "admissions-challenges",
    section: "Admission goals",
    prompt: "What are your biggest admission challenges?",
    placeholder: "For example: awareness, lead quality, follow-up, competition, conversion",
    type: "textarea",
  },
  {
    id: "audience-cities",
    section: "Target audience",
    prompt: "Which cities or regions do you want to target?",
    helper: "The proposal identifies North Bengal, Sikkim, Nepal, and Bhutan as potential focus areas.",
    placeholder: "List priority cities, regions, and countries",
    type: "textarea",
  },
  {
    id: "audience-school-type",
    section: "Target audience",
    prompt: "Are you targeting day-school families, boarding families, or both?",
    type: "single",
    options: ["Day school", "Boarding", "Both", "Not sure"],
  },
  {
    id: "audience-international",
    section: "Target audience",
    prompt: "Do you want to target international students?",
    type: "single",
    options: ["Yes", "No", "Possibly", "Already do"],
  },
  {
    id: "audience-parent-profile",
    section: "Target audience",
    prompt: "What is your ideal parent profile?",
    helper: "Consider location, profession, priorities, values, budget, and the education experience they seek.",
    placeholder: "Our ideal parent or guardian is...",
    type: "textarea",
  },
  {
    id: "audience-decision-maker",
    section: "Target audience",
    prompt: "Who makes the admission decision?",
    placeholder: "For example: parents jointly, one parent, guardian, student and parent",
    type: "text",
  },
  {
    id: "competitors-names",
    section: "Competitors",
    prompt: "Who are your top competitors?",
    placeholder: "List school names and locations",
    type: "textarea",
  },
  {
    id: "competitors-websites",
    section: "Competitors",
    prompt: "Which competitor websites do you admire?",
    placeholder: "Paste links and tell us what you like",
    type: "textarea",
  },
  {
    id: "competitors-campaigns",
    section: "Competitors",
    prompt: "Which competitor campaigns do you like?",
    placeholder: "Share links, examples, or a short description",
    type: "textarea",
  },
  {
    id: "marketing-platforms",
    section: "Marketing",
    prompt: "Which social media platforms do you currently use?",
    type: "multi",
    options: ["Instagram", "Facebook", "YouTube", "LinkedIn", "Google Business Profile", "Other"],
  },
  {
    id: "marketing-ads",
    section: "Marketing",
    prompt: "Are you currently running Google Ads or Meta Ads?",
    type: "multi",
    options: ["Google Ads", "Meta Ads", "Both", "Other paid ads", "No paid ads"],
  },
  {
    id: "marketing-budget-current",
    section: "Marketing",
    prompt: "What is your current monthly marketing budget?",
    helper: "Include ad spend and agency or production costs if known.",
    placeholder: "Amount and currency",
    type: "text",
  },
  {
    id: "leads-sources",
    section: "Lead management",
    prompt: "What are your current lead sources?",
    type: "multi",
    options: ["Website", "Organic search", "Social media", "Paid ads", "Referrals", "Events", "Walk-ins", "Education portals", "Other"],
  },
  {
    id: "leads-conversion-process",
    section: "Lead management",
    prompt: "What is your lead-to-admission conversion process, including calling scripts?",
    placeholder: "Describe qualification, counselling, calls, visits, forms, tests, and follow-up",
    type: "textarea",
  },
  {
    id: "leads-response-time",
    section: "Lead management",
    prompt: "What is your response time for a new enquiry?",
    type: "single",
    options: ["Under 15 minutes", "Under 1 hour", "Same business day", "Within 24 hours", "Longer than 24 hours", "Not tracked"],
  },
  {
    id: "leads-counsellor",
    section: "Lead management",
    prompt: "Who is the admission counsellor or team responsible for enquiries?",
    placeholder: "Name, role, or team",
    type: "text",
  },
  {
    id: "leads-follow-up",
    section: "Lead management",
    prompt: "What is your follow-up process?",
    placeholder: "Mention timing, channels, number of attempts, and any automation",
    type: "textarea",
  },
  {
    id: "leads-drop-off",
    section: "Lead management",
    prompt: "Where do leads drop off?",
    placeholder: "For example: before a call, after fees are shared, before the campus visit",
    type: "textarea",
  },
  {
    id: "admission-journey",
    section: "Admission process",
    prompt: "Describe the complete admission journey.",
    placeholder: "Discovery, enquiry, counselling, campus visit, application, assessment, admission...",
    type: "textarea",
  },
  {
    id: "admission-parent-drop-off",
    section: "Admission process",
    prompt: "Where do parents drop off?",
    placeholder: "Share the stage and any known reasons",
    type: "textarea",
  },
  {
    id: "technology-crm",
    section: "Technology",
    prompt: "Do you use a CRM or ERP?",
    placeholder: "Name the platform or describe the current setup",
    type: "text",
  },
  {
    id: "technology-analytics",
    section: "Technology",
    prompt: "Is Google Analytics installed?",
    type: "single",
    options: ["Yes and actively used", "Installed but rarely used", "No", "Not sure"],
  },
  {
    id: "technology-meta-pixel",
    section: "Technology",
    prompt: "Is the Meta Pixel installed?",
    type: "single",
    options: ["Yes", "Partially", "No", "Not sure"],
  },
  {
    id: "technology-gtm",
    section: "Technology",
    prompt: "Do you use Google Tag Manager?",
    type: "single",
    options: ["Yes", "No", "Not sure"],
  },
  {
    id: "technology-automation",
    section: "Technology",
    prompt: "Do you use marketing automation?",
    placeholder: "Name the tools or describe current automated workflows",
    type: "textarea",
  },
  {
    id: "content-photos",
    section: "Content assets",
    prompt: "Do you have professional photos?",
    type: "single",
    options: ["Yes, extensive", "Some", "Outdated", "No"],
  },
  {
    id: "content-videos",
    section: "Content assets",
    prompt: "Do you have professional videos?",
    type: "single",
    options: ["Yes, extensive", "Some", "Outdated", "No"],
  },
  {
    id: "content-testimonials",
    section: "Content assets",
    prompt: "Do you have parent or student testimonials?",
    type: "single",
    options: ["Yes, approved for use", "Some, approval needed", "No", "Not sure"],
  },
  {
    id: "content-drone",
    section: "Content assets",
    prompt: "Do you have drone footage of the campus?",
    type: "single",
    options: ["Yes", "Some", "No", "Planned"],
  },
  {
    id: "branding-guidelines",
    section: "Branding",
    prompt: "Do you have brand guidelines?",
    type: "single",
    options: ["Yes", "Partial guidelines", "No", "In progress"],
  },
  {
    id: "branding-logo",
    section: "Branding",
    prompt: "Do you have editable, high-resolution logo files?",
    type: "single",
    options: ["Yes", "Only basic image files", "No", "Not sure"],
  },
  {
    id: "branding-fonts",
    section: "Branding",
    prompt: "Which fonts does the school brand use?",
    placeholder: "List font names or say if they are not defined",
    type: "text",
  },
  {
    id: "branding-colours",
    section: "Branding",
    prompt: "What is the school's colour palette?",
    placeholder: "Colour names or hex codes",
    type: "text",
  },
  {
    id: "reviews-rating",
    section: "Reviews",
    prompt: "What is the school's current Google review rating?",
    helper: "Include the approximate number of reviews if available.",
    placeholder: "For example: 4.3 from 86 reviews",
    type: "text",
  },
  {
    id: "reviews-process",
    section: "Reviews",
    prompt: "What is your review collection process?",
    placeholder: "Describe how the school asks for, monitors, and responds to reviews",
    type: "textarea",
  },
  {
    id: "automation-chatbot",
    section: "AI automation priorities",
    prompt: "Is a website chatbot for admission enquiries a priority?",
    type: "single",
    options: ["High priority", "Useful later", "Already in place", "Not needed", "Not sure"],
  },
  {
    id: "automation-whatsapp",
    section: "AI automation priorities",
    prompt: "Are WhatsApp auto replies a priority?",
    type: "single",
    options: ["High priority", "Useful later", "Already in place", "Not needed", "Not sure"],
  },
  {
    id: "automation-assignment",
    section: "AI automation priorities",
    prompt: "Is automatic lead assignment to admission counsellors a priority?",
    type: "single",
    options: ["High priority", "Useful later", "Already in place", "Not needed", "Not sure"],
  },
  {
    id: "automation-booking",
    section: "AI automation priorities",
    prompt: "Is parent appointment booking for a campus visit a priority?",
    type: "single",
    options: ["High priority", "Useful later", "Already in place", "Not needed", "Not sure"],
  },
  {
    id: "budget-monthly",
    section: "Budget & timeline",
    prompt: "What monthly digital marketing budget are you considering?",
    helper: "Include currency and whether this includes media spend.",
    placeholder: "Budget range and currency",
    type: "text",
  },
  {
    id: "timeline-launch",
    section: "Budget & timeline",
    prompt: "What is your preferred launch date?",
    placeholder: "Choose a date",
    type: "date",
  },
  {
    id: "success-leads",
    section: "Success metrics",
    prompt: "What is your lead target?",
    placeholder: "Target per month or admission cycle",
    type: "text",
  },
  {
    id: "success-admissions",
    section: "Success metrics",
    prompt: "What is your admission target?",
    placeholder: "Target and academic period",
    type: "text",
  },
  {
    id: "success-cpl",
    section: "Success metrics",
    prompt: "What is your target cost per lead?",
    placeholder: "Amount and currency, or Not sure",
    type: "text",
  },
  {
    id: "success-traffic",
    section: "Success metrics",
    prompt: "What is your website traffic goal?",
    placeholder: "For example: qualified monthly visits, prospectus downloads, campus bookings",
    type: "textarea",
  },
];
